AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Expense Claim Approval System

Parameters:
  Environment:
    Type: String
    Default: Prod

Resources:
  # API Gateway to submit claims via triggering the ClaimsApprovalStateMachine
  ClaimsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-ClaimsApi"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'OPTIONS, POST, GET'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'" # TODO Do not use this in Production
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false

  # Step function to orchestrate the whole claims submission and approval flow
  ClaimsApprovalStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-ClaimsApprovalStateMachine"
      DefinitionUri: statemachines/claims_approval_process.asl.json
      DefinitionSubstitutions:
        SNS_TOPIC_ARN: !Ref ClaimsNotificationTopic
        DYNAMODB_TABLE_NAME: !Ref ClaimsTable
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ClaimsNotificationTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref ClaimsTable

  # Lambda function to handle submitting claims
  SubmitClaimsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-SubmitClaimsFunction"
      Handler: functions/handlers/submit-claim.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref ClaimsApprovalStateMachine
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref ClaimsApprovalStateMachine
      Events:
        SubmitApi:
          Type: Api
          Properties:
            Path: /claims
            Method: post
            RestApiId: !Ref ClaimsApi

  # Lambda function to handle manual approvals and rejections
  ApproveClaimsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ApproveClaimsFunction"
      Handler: functions/handlers/approve-claim.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ClaimsTable
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
              Resource: "*"
        - DynamoDBReadPolicy:
            TableName: !Ref ClaimsTable
      Events:
        ApproveApi:
          Type: Api
          Properties:
            Path: /claims/approve/{claimId}
            Method: post
            RestApiId: !Ref ClaimsApi
        RejectApi:
          Type: Api
          Properties:
            Path: /claims/reject/{claimId}
            Method: post
            RestApiId: !Ref ClaimsApi

  ListPendingClaimsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ListPendingClaimsFunction"
      Handler: functions/handlers/list-pending-claims.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ClaimsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ClaimsTable
      Events:
        ListPendingClaimsApi:
          Type: Api
          Properties:
            Path: /claims/pending-claims
            Method: get
            RestApiId: !Ref ClaimsApi

  # SNS topic to notify when claims submitted, approved and rejected
  ClaimsNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-ClaimsNotificationTopic"

  # DynamoDB table to store claim details
  ClaimsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
#      TableName: !Sub "${AWS::StackName}-ClaimsTable"
      PrimaryKey:
        Name: claimId
        Type: String

  # Replace with your own email
#  ClaimsNotificationTopicSubscription1:
#    Type: AWS::SNS::Subscription
#    Properties:
#      Endpoint: test@example.com
#      Protocol: email
#      TopicArn: !Ref ClaimsNotificationTopic

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-user-pool"
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      Schema:
        - Name: email
          Required: true
          Mutable: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub "${AWS::StackName}-client"
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - !Sub "https://${CloudFrontDistribution.DomainName}/index.html"
        - !Sub "https://${CloudFrontDistribution.DomainName}/"
        - "http://localhost:8080/index.html"
        - "http://localhost:8080/"
      LogoutURLs:
        - !Sub "https://${CloudFrontDistribution.DomainName}/index.html"
        - !Sub "https://${CloudFrontDistribution.DomainName}/"
        - "http://localhost:8080/index.html"
        - "http://localhost:8080/"

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${AWS::StackName}-${AWS::AccountId}"
      UserPoolId: !Ref CognitoUserPool

  # S3 Bucket to host single page app website
  WebSiteBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled

  WebSiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WebSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: "PolicyForCloudFrontPrivateContent"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref WebSiteBucket, "/*" ] ]
            Condition:
              StringEquals:
                "AWS:SourceArn": !Join [ "", [ "arn:aws:cloudfront::", !Ref "AWS::AccountId", ":distribution/", !Ref CloudFrontDistribution ] ]

  # CloudFront Function to rewrite requests for subdirectory index.html files
  CloudFrontIndexRewriterFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${AWS::StackName}-IndexRewriter"
      AutoPublish: true
      FunctionConfig:
        Comment: "Rewrites subdirectory requests to /index.html"
        Runtime: cloudfront-js-2.0
      FunctionCode: |
        function handler(event) {
            var request = event.request;
            var uri = request.uri;
            
            // If the URI ends with '/', append 'index.html'
            if (uri.endsWith('/')) {
                request.uri += 'index.html';
            } 
            // If the URI doesn't have a '.' (no extension), append '/index.html'
            else if (!uri.includes('.')) {
                request.uri += '/index.html';
            }

            return request;
        }

  # CloudFront Distribution for hosting the single page app website
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebSiteBucket.RegionalDomainName
            Id: "myS3Origin"
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        Enabled: true
        DefaultRootObject: "index.html"
        HttpVersion: "http2"
        DefaultCacheBehavior:
          AllowedMethods:
            - "DELETE"
            - "GET"
            - "HEAD"
            - "OPTIONS"
            - "PATCH"
            - "POST"
            - "PUT"
          CachedMethods:
            - "GET"
            - "HEAD"
          TargetOriginId: "myS3Origin"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
          ViewerProtocolPolicy: "allow-all"
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 86400
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt CloudFrontIndexRewriterFunction.FunctionMetadata.FunctionARN
        PriceClass: "PriceClass_200"
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
  CloudFrontOriginAccessControl:
    Type: "AWS::CloudFront::OriginAccessControl"
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${WebSiteBucket} OAC"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: "always"
        SigningProtocol: "sigv4"

Outputs:
  ClaimsApiUrl:
    Description: "Claims API Gateway URL"
    Value: !Sub "https://${ClaimsApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID for hosting web front end"
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: "CloudFront Distribution Domain Name for accessing web front end"
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebS3BucketName:
    Description: "S3 Bucket for hosting web frontend"
    Value: !Ref WebSiteBucket
  CognitoDomain:
    Description: "Cognito User Pool Domain"
    Value: !Sub "https://${CognitoUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
  CognitoClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient
  CognitoAuthority:
    Description: "Cognito OIDC Authority URL"
    Value: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
